# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
# 
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

require 'prime'

limit = ARGV[0].to_i

i = 1
sum = 0
while true
  sum += i
  factors = 0
  #lfactor = 0
  if sum.prime?
    i += 1
    next
  end
  1.step(Math.sqrt(sum).to_i, 1).each do |n|
    if (sum % n == 0)
      factors += 2
    end
  end
  if (factors > limit)
    abort("Triangle number #{sum} has #{factors}, #{factors-limit} over the limit #{limit}")
  end
  puts "#{i}\t\t#{sum}\t\t#{factors}"
  i += 1
end
